// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04NWzVbA7Ky2k7jApwMZiEmYHf3Uw1lo',
    appId: '1:1098143851188:web:5d3afab2eeb8be7f842de1',
    messagingSenderId: '1098143851188',
    projectId: 'push-notification-practi-915f2',
    authDomain: 'push-notification-practi-915f2.firebaseapp.com',
    storageBucket: 'push-notification-practi-915f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqDTNWxPd_TORc6an8bOtaQgC5TbPv02o',
    appId: '1:1098143851188:android:d21544727e380008842de1',
    messagingSenderId: '1098143851188',
    projectId: 'push-notification-practi-915f2',
    storageBucket: 'push-notification-practi-915f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_wS6MjSBf34MHETGc2tzR3XukWetpZK8',
    appId: '1:1098143851188:ios:4da142e5a2b29afa842de1',
    messagingSenderId: '1098143851188',
    projectId: 'push-notification-practi-915f2',
    storageBucket: 'push-notification-practi-915f2.firebasestorage.app',
    iosBundleId: 'com.example.pushnotificationPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_wS6MjSBf34MHETGc2tzR3XukWetpZK8',
    appId: '1:1098143851188:ios:4da142e5a2b29afa842de1',
    messagingSenderId: '1098143851188',
    projectId: 'push-notification-practi-915f2',
    storageBucket: 'push-notification-practi-915f2.firebasestorage.app',
    iosBundleId: 'com.example.pushnotificationPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB04NWzVbA7Ky2k7jApwMZiEmYHf3Uw1lo',
    appId: '1:1098143851188:web:17ced868cbff2b42842de1',
    messagingSenderId: '1098143851188',
    projectId: 'push-notification-practi-915f2',
    authDomain: 'push-notification-practi-915f2.firebaseapp.com',
    storageBucket: 'push-notification-practi-915f2.firebasestorage.app',
  );
}
